import java.sql.*;
import javax.swing.JOptionPane;
import lib.koneksi;
import javax.swing.table.DefaultTableModel;
import java.awt.event.ActionEvent;


public class FEditBarang extends javax.swing.JInternalFrame {
    koneksi konek = new koneksi();
    private ActionEvent evt;
    String pilKode, pilNama, pilStok;
    /**
     * Creates new form FEditBarang
     */
    public FEditBarang() {
        initComponents();
        this.btRefreshActionPerformed(evt);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfkode = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfnama = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfstok = new javax.swing.JTextField();
        btRefresh = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTb1 = new javax.swing.JTable();
        btUbah = new javax.swing.JButton();
        btHapus = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("EDIT DATA BARANG");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("KODE BARANG");

        tfkode.setEditable(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("NAMA BARANG");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("STOK");

        tfstok.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tfstok.setText("0");
        tfstok.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfstokKeyTyped(evt);
            }
        });

        btRefresh.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btRefresh.setText("refresh");
        btRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRefreshActionPerformed(evt);
            }
        });

        jTb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NO", "KODE BARANG", "NAMA BARANG", "STOK"
            }
        ));
        jTb1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTb1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTb1);

        btUbah.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btUbah.setText("UBAH");
        btUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUbahActionPerformed(evt);
            }
        });

        btHapus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btHapus.setText("HAPUS");
        btHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(btUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btRefresh))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfkode, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfnama, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfstok, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(144, 144, 144)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btRefresh)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfkode)
                                .addGap(4, 4, 4)))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfnama, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfstok, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfstokKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfstokKeyTyped
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_tfstokKeyTyped

    private void btRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRefreshActionPerformed
        DefaultTableModel tb = new DefaultTableModel();
        tb.addColumn("N0");
        tb.addColumn("KODE BARANG");
        tb.addColumn("NAMA BARANG");
        tb.addColumn("STOK");
        try{
            String sql = "Select * from t_barang";
            Statement st = konek.getKoneksi().createStatement();
            ResultSet has = st.executeQuery(sql);
            int no = 0;
            while(has.next()){
                no = no + 1;
                tb.addRow(new Object[]{no, has.getString(1), has.getString(2), has.getString(3)});
            }
            jTb1.setModel(tb);
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,"error" +e);
        }
    }//GEN-LAST:event_btRefreshActionPerformed

    private void jTb1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTb1MouseClicked
        int i = this.jTb1.getSelectedRow();
    if(i == -1){
        return;
    }
    pilKode = (String) this.jTb1.getValueAt(i, 1);
    tfkode.setText(pilKode);
    pilNama = (String) this.jTb1.getValueAt(i, 2);
    tfnama.setText(pilNama);
    pilStok = (String) this.jTb1.getValueAt(i, 3);
    tfstok.setText(pilStok);
    }//GEN-LAST:event_jTb1MouseClicked

    private void btHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHapusActionPerformed
    String hapus = "Delete from t_barang where idBarang = '"+pilKode+"'";
    if(JOptionPane.showConfirmDialog(null, "Apakah Anda Yakin Menghapus Data "+pilKode+" ini??","Information",
            JOptionPane.OK_CANCEL_OPTION,JOptionPane.INFORMATION_MESSAGE)==JOptionPane.OK_OPTION){
        try{
            Statement st = konek.getKoneksi().createStatement();
            st.executeUpdate(hapus);
            st.close();
            JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
            this.btRefreshActionPerformed(evt);
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, "Terjadi Kesalahan : "+ e);
        }
    }else
        this.btRefreshActionPerformed(evt);
    tfkode.setText("");
    tfnama.setText("");
    tfstok.setText("0");
    }//GEN-LAST:event_btHapusActionPerformed

    private void btUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUbahActionPerformed
    String kode = tfkode.getText();
    String nama = tfnama.getText();
    int stok;
        if(!tfstok.getText().equals(""))
        {stok = Integer.parseInt(tfstok.getText());}
        else
        {stok = 0;}
        
    if(!tfstok.getText().isEmpty() && !nama.isEmpty()){
        String sql = "UPDATE t_barang set nama='"+nama+"', stok'"+stok+"' where idBarang='"+kode+"'";
            try{
                Statement s = konek.getKoneksi().createStatement();
                s.executeUpdate(sql);
                s.close();
                JOptionPane.showMessageDialog(null,"Data Berhasil Diubah");
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,"Data Gagal Diubah : "+ e);
            }
    }else{
        JOptionPane.showMessageDialog(null,"Nama Barang Dan Jumlah Stok Harus Diisi Dengan Benar !!!");
    }
    this.btRefreshActionPerformed(evt);
    tfkode.setText("");
    tfnama.setText("");
    tfstok.setText("0");
    }//GEN-LAST:event_btUbahActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btHapus;
    private javax.swing.JButton btRefresh;
    private javax.swing.JButton btUbah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTb1;
    private javax.swing.JTextField tfkode;
    private javax.swing.JTextField tfnama;
    private javax.swing.JTextField tfstok;
    // End of variables declaration//GEN-END:variables
}
