import java.sql.*;
import javax.swing.JOptionPane;
import lib.koneksi;
import javax.swing.table.DefaultTableModel;
import java.awt.event.ActionEvent;

public class FTampilBarang extends javax.swing.JInternalFrame {
private koneksi konek = new koneksi();
private ActionEvent evt;
    /**
     * Creates new form FTampilBarang
     */
    public FTampilBarang() {
        initComponents();
        this.btTampilActionPerformed(evt);
    }

    private void cari(){
     DefaultTableModel tb = new DefaultTableModel();
     tb.addColumn("NO");
     tb.addColumn("KODE BARANG");
     tb.addColumn("NAMA BARANG");
     tb.addColumn("STOK");
     try{
         String sqlCari ="Select * from t_barang where nama LIKE'%"+tfKunci.getText()+"%'";
         Statement st = konek.getKoneksi().createStatement();
         ResultSet hasil = st.executeQuery(sqlCari);
         
         int no = 0;
         while(hasil.next()){
             no = no + 1;
             tb.addRow(new Object[]{no,hasil.getString(1),hasil.getString(2), hasil.getString(3)});
         }
         jTb1.setModel(tb);
     }catch(Exception e){
         JOptionPane.showMessageDialog(this, "error : " + e);
     }
}    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTb1 = new javax.swing.JTable();
        btTampil = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btCari = new javax.swing.JButton();
        tfKunci = new javax.swing.JTextField();
        btCetak = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Tampil Data Barang");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("DATA BARANG");

        jTb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N0", "KODE BARANG", "NAMA BARANG", "STOK"
            }
        ));
        jScrollPane1.setViewportView(jTb1);

        btTampil.setText("Refresh");
        btTampil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTampilActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Cari Nama Barang :");

        btCari.setText("Cari");
        btCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCariActionPerformed(evt);
            }
        });

        tfKunci.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfKunciKeyPressed(evt);
            }
        });

        btCetak.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btCetak.setText("CETAK");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 220, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfKunci)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btCari)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btTampil, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btCetak)
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btTampil)
                    .addComponent(btCari)
                    .addComponent(tfKunci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btCetak)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btTampilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTampilActionPerformed
     DefaultTableModel tabelku = new DefaultTableModel();
     tabelku.addColumn("NO");
     tabelku.addColumn("KODE BARANG");
     tabelku.addColumn("NAMA BARANG");
     tabelku.addColumn("STOK");
     
     try{
         String sql = "Select * from t_barang";
         Statement st = konek.getKoneksi().createStatement();
         ResultSet hasil = st.executeQuery(sql);
         
         int no = 0;
         while(hasil.next()){
             no = no + 1;
             tabelku.addRow(new Object[] {no,hasil.getString(1),hasil.getString(2), hasil.getString(3)});
         }
         jTb1.setModel(tabelku);
     }catch (Exception e){
         JOptionPane.showMessageDialog(this, "error : " +e);
     }
    }//GEN-LAST:event_btTampilActionPerformed

    private void btCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCariActionPerformed
        cari();
    }//GEN-LAST:event_btCariActionPerformed

    private void tfKunciKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfKunciKeyPressed
        cari();
    }//GEN-LAST:event_tfKunciKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCari;
    private javax.swing.JButton btCetak;
    private javax.swing.JButton btTampil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTb1;
    private javax.swing.JTextField tfKunci;
    // End of variables declaration//GEN-END:variables
}
